require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const User = require('./models/User');
const Car = require('./models/Car');
const Offer = require('./models/Offer');
const connectDB = require('./config/db');

const placeholder = 'https://res.cloudinary.com/ddpmrivna/image/upload/v1/prestige-motors/placeholder-car';

const importData = async () => {
  try {
    await connectDB();
    
    await Offer.deleteMany();
    await Car.deleteMany();
    await User.deleteMany();

    // 1. Master Admin
    await User.create({
      firstName: 'Master', lastName: 'Admin',
      email: 'admin@prestigemotors.com', phone: '0000000000',
      passwordHash: 'Admin@123', role: 'admin'
    });

    // 2. All Cars
    const cars = [
      // ===================== NISSAN — NEW =====================
      { category:'new', brand:'Nissan', model:'Sunny 2026 M/T', year:2026, price:645000, mileage:0, fuelType:'Petrol', transmission:'Manual', bodyType:'Sedan', overview:'Cheap-to-run compact sedan, very common in Egypt, easy parts and resale.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Nissan', model:'Sunny 2026 A/T Base', year:2026, price:695000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Same Sunny formula but easier daily driving in Cairo traffic.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Nissan', model:'Sunny 2026 A/T', year:2026, price:765000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Same Sunny formula, but easier to move in the market because many Cairo buyers want automatic.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Nissan', model:'Sentra 2025 Baseline', year:2025, price:999000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Bigger and more refined than Sunny, stronger family-sedan choice.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Nissan', model:'Qashqai 2025 N-Connecta', year:2025, price:1499000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Popular compact crossover with better comfort and road presence than sedan options.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Nissan', model:'Qashqai Facelift 2026', year:2026, price:1409900, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Well-known compact crossover with better image and comfort than entry sedans.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Nissan', model:'Juke 2026', year:2026, price:1060000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Smaller urban crossover with younger styling and decent showroom appeal.', images:[placeholder], listingStatus:'approved' },
      // ===================== NISSAN — USED =====================
      { category:'used', brand:'Nissan', model:'Sunny 2022 (50k km)', year:2022, price:620000, mileage:50000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Entry-level sedan with cheap running costs and very liquid resale market.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Nissan', model:'Sunny 2022 (30k km)', year:2022, price:670000, mileage:30000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Strong used-budget stock because it sells on practicality, not excitement.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Nissan', model:'Sunny 2022 (140k km)', year:2022, price:620000, mileage:140000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'High-mileage but still realistic stock for price-focused customers.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Nissan', model:'Tiida 2015', year:2015, price:600000, mileage:150000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Hatchback', overview:'Older but still desirable for buyers who want Japanese reliability on a tighter budget.', images:[placeholder], listingStatus:'approved' },
      // ===================== HYUNDAI — NEW =====================
      { category:'new', brand:'Hyundai', model:'Accent RB 2026', year:2026, price:759900, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Basic mainstream sedan with strong recognition and easy resale.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Hyundai', model:'Elantra AD 2026', year:2026, price:1020000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Familiar Egyptian market sedan, easy to display and easy to explain to buyers.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Hyundai', model:'Elantra CN7 2025', year:2025, price:1375000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'More modern and sharper-looking than AD, with stronger showroom presence.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Hyundai', model:'Tucson GDI 2026', year:2026, price:1625000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Mainstream SUV with strong brand pull, comfortable ride, and broad demand.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Hyundai', model:'Tucson 2026', year:2026, price:1625000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'One of the strongest mainstream SUV names in Egypt, broad demand.', images:[placeholder], listingStatus:'approved' },
      // ===================== HYUNDAI — USED =====================
      { category:'used', brand:'Hyundai', model:'Elantra AD 2020 (111k)', year:2020, price:750000, mileage:111000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Strong used-market sedan; comfortable, familiar, and easy to move.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Hyundai', model:'Elantra AD 2020', year:2020, price:711000, mileage:80000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Reliable used sedan that moves well with families and commuters.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Hyundai', model:'Elantra AD 2019', year:2019, price:820000, mileage:200000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Higher mileage, but still attractive when priced right because the model is known and trusted.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Hyundai', model:'Tucson 2021 (67k)', year:2021, price:1390000, mileage:67000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Very desirable used SUV in Egypt; broad appeal for family buyers.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Hyundai', model:'Tucson 2021 (107k)', year:2021, price:1300000, mileage:107000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Strong family SUV stock with high market liquidity.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Hyundai', model:'Tucson GDI 2021', year:2021, price:1470000, mileage:90000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'More desirable used Tucson variant for buyers chasing nicer trim and newer shape.', images:[placeholder], listingStatus:'approved' },
      // ===================== KIA — NEW =====================
      { category:'new', brand:'Kia', model:'Grand Cerato 2024', year:2024, price:1299900, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'One of the most familiar compact sedans in Egypt, easy showroom stock.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Kia', model:'Grand Cerato 2024 EX Cam', year:2024, price:1429900, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Better-equipped Grand Cerato for buyers who care about features and camera package.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Kia', model:'Seltos 2025', year:2025, price:1524900, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Compact crossover that works well for younger buyers wanting a Korean badge and SUV look.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Kia', model:'K4 2026 GT-Line', year:2026, price:1599900, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'More modern compact sedan option for people bored of the usual Cerato look.', images:[placeholder], listingStatus:'approved' },
      // ===================== KIA — USED =====================
      { category:'used', brand:'Kia', model:'Sportage 2021 (80k)', year:2021, price:1450000, mileage:80000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'High-demand used SUV with strong showroom appeal and fast turnover potential.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Kia', model:'Sportage 2021 (120k)', year:2021, price:1250000, mileage:120000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'High-demand used SUV and one of the easier mid-range crossovers to sell.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Kia', model:'Sportage 2021 (82k)', year:2021, price:1350000, mileage:82000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Better-mileage showroom stock with broader appeal.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Kia', model:'Sportage 2022 (7k)', year:2022, price:1470000, mileage:6850, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Near-new SUV stock, useful if you want something between factory-new and regular used.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Kia', model:'Sportage 2022', year:2022, price:1000000, mileage:50000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Still a hot used SUV line in the Egyptian market.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Kia', model:'Grand Cerato 2022', year:2022, price:900000, mileage:172500, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Popular compact sedan with solid market recognition, though this specific mileage is high.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Kia', model:'Grand Cerato 2019', year:2019, price:890000, mileage:133000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Common used sedan with easy recognition and straightforward showroom positioning.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Kia', model:'XCeed 2022', year:2022, price:1070000, mileage:70000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Niche crossover-hatch option for buyers wanting something less common than Sportage.', images:[placeholder], listingStatus:'approved' },
      // ===================== MG — NEW =====================
      { category:'new', brand:'MG', model:'5 2026 Comfort', year:2026, price:800000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Stylish compact sedan, usually chosen for features and shape over the Sunny.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'MG', model:'5 2026 Standard', year:2026, price:799990, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Good-looking budget sedan, a common alternative to Sunny and Arrizo.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'MG', model:'ZS 2026 Comfort', year:2026, price:930000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'One of the common compact crossovers in the market, practical and easy to place in a showroom lineup.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'MG', model:'GT 2026 Comfort', year:2026, price:999990, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Sportier styling than MG 5, aimed at buyers who want shape first.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'MG', model:'RX5 Plus 2026 Luxury', year:2026, price:1380000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Bigger and more premium-feeling than ZS, better for a mid-range SUV lineup.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'MG', model:'HS 2026 Luxury', year:2026, price:1525000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Strong upper-mainstream SUV with good shape and decent perceived value.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'MG', model:'7 2026 Luxury', year:2026, price:1590000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Fastback', overview:'Flagship-ish MG sedan with much stronger road presence than MG 5.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'MG', model:'4 2026 Standard', year:2026, price:1200000, mileage:0, fuelType:'Electric', transmission:'Automatic', bodyType:'Hatchback', overview:'Useful EV showroom piece if you want one affordable electric badge in the lineup.', images:[placeholder], listingStatus:'approved' },
      // ===================== MG — USED =====================
      { category:'used', brand:'MG', model:'5 2022 (80k)', year:2022, price:700000, mileage:80000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Good-looking used compact sedan that attracts buyers wanting newer shape and features.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'MG', model:'5 2021', year:2021, price:675000, mileage:128000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Budget-friendly used sedan for customers wanting newer shape at lower money.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'MG', model:'5 2022 (70k)', year:2022, price:795000, mileage:70000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Easy used-sedan stock for customers wanting modern shape without Corolla pricing.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'MG', model:'5 2020', year:2020, price:749999, mileage:56000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Lower-year-value entry point into the MG used market.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'MG', model:'ZS 2025', year:2025, price:950000, mileage:27000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Near-new crossover stock, useful if you want showroom inventory between new and normal used.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'MG', model:'RX5 2021', year:2021, price:995000, mileage:125000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Practical used SUV for buyers wanting size over badge prestige.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'MG', model:'6 2021', year:2021, price:750000, mileage:168000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Higher-mileage but more premium-feeling than MG 5.', images:[placeholder], listingStatus:'approved' },
      // ===================== CHERY — NEW =====================
      { category:'new', brand:'Chery', model:'Arrizo 5 2026 CVT Highline', year:2026, price:755000, mileage:0, fuelType:'Petrol', transmission:'CVT', bodyType:'Sedan', overview:'Budget sedan aimed at price-sensitive buyers who still want decent features.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Chery', model:'Tiggo 4 Pro 2026 Comfort', year:2026, price:875000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Small crossover with strong value-for-money positioning in Egypt.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Chery', model:'Tiggo 7 2026 Baseline', year:2026, price:965000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Mid-size Chinese SUV with spacious cabin and aggressive pricing.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Chery', model:'Arrizo 5 2026', year:2026, price:695000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'One of the most obvious budget-sedan choices in Egypt right now.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Chery', model:'Tiggo 7 2026 Highline', year:2026, price:1035000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Better trim version of the Tiggo 7 for customers wanting more equipment.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Chery', model:'Tiggo 7 Pro Max 2026', year:2026, price:1230000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'More upscale Chery offering with stronger cabin/features pitch.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Chery', model:'Tiggo 8 Pro Max 2026', year:2026, price:1490000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Larger family SUV, stronger as a top-end Chinese showroom piece.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Chery', model:'EQ7 2026', year:2026, price:1599000, mileage:0, fuelType:'Electric', transmission:'Automatic', bodyType:'SUV', overview:'Electric SUV option for a showroom that wants some EV presence.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Chery', model:'Tiggo 9 2026', year:2026, price:1999000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Large flagship-style Chery SUV, useful as a premium Chinese option.', images:[placeholder], listingStatus:'approved' },
      // ===================== CHERY — USED =====================
      { category:'used', brand:'Chery', model:'Tiggo 7 2022', year:2022, price:850000, mileage:70000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Used Chinese SUV with decent size and equipment, attractive to value-focused SUV buyers.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Chery', model:'Tiggo 7 Pro 2022', year:2022, price:975000, mileage:44000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Better-looking and more upscale-feeling than base Tiggo models, useful mid-range SUV stock.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Chery', model:'Arrizo 5 2026', year:2026, price:700000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Technically listed in the market already; useful when sourcing near-new stock from dealers.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Chery', model:'Tiggo 4 Pro 2026', year:2026, price:915000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Common market-listed Chinese crossover with strong value positioning.', images:[placeholder], listingStatus:'approved' },
      // ===================== BYD — NEW =====================
      { category:'new', brand:'BYD', model:'F3 2025 M/T', year:2025, price:720000, mileage:0, fuelType:'Petrol', transmission:'Manual', bodyType:'Sedan', overview:'Basic low-cost sedan; not exciting, but it sells on price.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'BYD', model:'F3 2025 A/T', year:2025, price:700000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Cheap automatic option for buyers who want the lowest entry price possible.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'BYD', model:'Seagull 2025', year:2025, price:777000, mileage:0, fuelType:'Electric', transmission:'Automatic', bodyType:'Hatchback', overview:'Small EV, city-focused, good as an affordable electric entry piece in the showroom.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'BYD', model:'Dolphin 2026', year:2026, price:849900, mileage:0, fuelType:'Electric', transmission:'Automatic', bodyType:'Hatchback', overview:'Affordable EV hatchback and one of the cleaner electric entries for urban buyers.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'BYD', model:'Sealion 6 2026 EV', year:2026, price:1549900, mileage:0, fuelType:'Electric', transmission:'Automatic', bodyType:'SUV', overview:'Newer electric SUV product that gives the showroom a more advanced-tech angle.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'BYD', model:'Sealion 6 2026 DM-i Ultra', year:2026, price:1749900, mileage:0, fuelType:'Hybrid', transmission:'Automatic', bodyType:'SUV', overview:'Plug-in-hybrid family SUV for customers not ready to go full EV.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'BYD', model:'Sealion 6 2026 DM-i Luxury', year:2026, price:1949900, mileage:0, fuelType:'Hybrid', transmission:'Automatic', bodyType:'SUV', overview:'Higher trim of the Sealion 6, useful as a premium EV/PHEV Chinese choice.', images:[placeholder], listingStatus:'approved' },
      // ===================== BYD — USED =====================
      { category:'used', brand:'BYD', model:'F3 2022', year:2022, price:525000, mileage:45000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Cheap used automatic sedan, useful for the low-budget end of your stock mix.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'BYD', model:'F3 2024 M/T', year:2024, price:600000, mileage:47053, fuelType:'Petrol', transmission:'Manual', bodyType:'Sedan', overview:'Very basic but attractive for buyers who care about price first.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'BYD', model:'F3 2025', year:2025, price:700000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Market-listed newish stock for a buyer who just wants the cheapest automatic sedan.', images:[placeholder], listingStatus:'approved' },
      // ===================== JETOUR — NEW =====================
      { category:'new', brand:'Jetour', model:'X70 2026 Comfort', year:2026, price:1030000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Roomy Chinese SUV aimed at families wanting size without Toyota money.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Jetour', model:'X70 2026 Luxury', year:2026, price:1150000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Better-equipped X70 trim, a practical showroom option for value-focused families.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Jetour', model:'X70 Plus Luxury Local 2026', year:2026, price:1160000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Local-assembly style X70 Plus variant with a more modern look than the base X70.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Jetour', model:'Dashing 2026', year:2026, price:1155000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'More design-focused crossover with better showroom appeal than plain family SUVs.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Jetour', model:'Dashing Comfort 2025', year:2025, price:1480000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'More design-focused crossover with better showroom appeal than plain family SUVs.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Jetour', model:'Dashing 1.5 Luxury 2025', year:2025, price:1439000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Better trim Dashing for buyers who care about styling and equipment.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Jetour', model:'Dashing 1.6 Luxury 2025', year:2025, price:1639000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Stronger-engine Dashing version, better suited for customers wanting a more premium feel.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Jetour', model:'T1 Luxury 2026', year:2026, price:1585000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Off-road SUV', overview:'Rugged-looking SUV, one of the stronger image cars in Jetour\'s Egypt lineup.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Jetour', model:'T1 Matt Colour 2026', year:2026, price:1635000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Off-road SUV', overview:'Matte-color T1 for buyers who want the more visual spec instead of the standard look.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Jetour', model:'T2 Luxury 2026', year:2026, price:1775000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Off-road SUV', overview:'Higher-end rugged Jetour that stands out more than typical crossover stock.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Jetour', model:'T2 Matt Colour 2026', year:2026, price:1825000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Off-road SUV', overview:'Matte-color T2, mainly a visual/presentation upgrade for higher-end showroom stock.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Jetour', model:'X90 Plus Luxury 2026', year:2026, price:1520000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Larger three-row style SUV for families wanting more cabin space.', images:[placeholder], listingStatus:'approved' },
      // ===================== JETOUR — USED =====================
      { category:'used', brand:'Jetour', model:'X70S 2021', year:2021, price:865000, mileage:50000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Value-focused used family SUV with decent size and price positioning.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Jetour', model:'X70S 2026', year:2026, price:1030000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Dealer-stocked near-new Jetour, useful if you want cars sourced from the market rather than direct factory allocation.', images:[placeholder], listingStatus:'approved' },
      // ===================== TOYOTA — NEW =====================
      { category:'new', brand:'Toyota', model:'Corolla 2026', year:2026, price:1500000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Benchmark compact sedan for reliability, resale, and brand trust.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Toyota', model:'Land Cruiser 2026', year:2026, price:8300000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Full-size SUV', overview:'Flagship SUV with huge brand prestige and high-end showroom appeal.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Toyota', model:'Corolla 2026 Comfort', year:2026, price:1250000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'One of the safest showroom bets in Egypt for resale, trust, and family demand.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Toyota', model:'Urban Cruiser 2026 Active', year:2026, price:1300000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Compact crossover for buyers wanting Toyota badge without RAV4 money.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Toyota', model:'Urban Cruiser 2026 Comfort', year:2026, price:1400000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Slightly higher trim, still a practical Toyota crossover showroom item.', images:[placeholder], listingStatus:'approved' },
      // ===================== TOYOTA — USED =====================
      { category:'used', brand:'Toyota', model:'Corolla 2021 (78k)', year:2021, price:1050000, mileage:78000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Very safe stock for a showroom because demand and resale are consistently strong.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Toyota', model:'Corolla 2021 (60k)', year:2021, price:1100000, mileage:60000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Extremely liquid used stock; not cheap, but easy to place.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Toyota', model:'Corolla 2021 (70k)', year:2021, price:990000, mileage:70000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Same formula, slightly lower asking price and still attractive.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Toyota', model:'Corolla 2022', year:2022, price:1017000, mileage:50000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Still premium-priced in used market because Corolla resale stays strong.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Toyota', model:'Corolla 2023', year:2023, price:1106000, mileage:30000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Near-new used option for customers who want a Corolla without waiting for factory stock.', images:[placeholder], listingStatus:'approved' },
      // ===================== SKODA — USED =====================
      { category:'used', brand:'Skoda', model:'Octavia 2021', year:2021, price:1120000, mileage:120000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'European compact sedan with stronger cabin feel and road manners than many rivals.', images:[placeholder], listingStatus:'approved' },
      // ===================== GAC — NEW =====================
      { category:'new', brand:'GAC', model:'GS3 Emzoom GS 2026', year:2026, price:920000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Compact crossover with modern styling and strong value.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'GAC', model:'GS3 Emzoom GB 2026', year:2026, price:1029000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Better-equipped Emzoom trim with stronger feature set for showroom display.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'GAC', model:'GS3 Emzoom GL 2026', year:2026, price:1099000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Higher trim Emzoom aimed at buyers who care more about equipment and presentation.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'GAC', model:'GS3 Emzoom R-Style 2026', year:2026, price:1199000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Crossover', overview:'Sportier-looking top Emzoom trim that works well as a showroom attention piece.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'GAC', model:'Empow GS 2026', year:2026, price:995000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Compact sporty sedan, positioned for buyers who want something less boring.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'GAC', model:'Empow GB 2026', year:2026, price:1099000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Mid-trim Empow with decent value and stronger spec sheet than the base version.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'GAC', model:'Empow GE S-Style 2026', year:2026, price:1199000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'More aggressive trim of the Empow for buyers who care about styling and image.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'GAC', model:'GS4 GS 2025', year:2025, price:1185000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Mid-size crossover with a more family-oriented pitch.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'GAC', model:'GS4 GB 2025', year:2025, price:1265000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Better trim GS4 for customers wanting more comfort and features.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'GAC', model:'GS4 Max Premium 2026', year:2026, price:1249000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Larger and newer GS4 Max trim, suitable as an upper-mainstream showroom SUV.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'GAC', model:'Emkoo GS 2025', year:2025, price:1345000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'More upscale GAC crossover with stronger design and better cabin feel.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'GAC', model:'Emkoo GE 2025', year:2025, price:1455000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Better-equipped Emkoo, useful if you want a richer-looking Chinese SUV in the lineup.', images:[placeholder], listingStatus:'approved' },
      // ===================== BMW — NEW =====================
      { category:'new', brand:'BMW', model:'118 2025 M Sport', year:2025, price:2450000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Hatchback', overview:'Entry BMW badge car, useful as premium gateway stock.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'BMW', model:'218i 2025 M Sport', year:2025, price:2650000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Gran Coupe', overview:'Lower-entry premium sedan-like option with strong badge value.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'BMW', model:'X1 2025 X Line', year:2025, price:2950000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Compact premium SUV, practical and easier to sell than niche BMWs.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'BMW', model:'X3 2026 xLine', year:2026, price:4100000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Stronger road presence and more practical premium SUV stock.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'BMW', model:'420 2025 M Sport', year:2025, price:4650000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Coupe', overview:'Image car more than volume car, but good for showroom attention.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'BMW', model:'X5 2025 xDrive40i xLine', year:2025, price:7100000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Serious premium SUV stock, good for upper-end buyers.', images:[placeholder], listingStatus:'approved' },
      // ===================== BMW — USED =====================
      { category:'used', brand:'BMW', model:'320 2020 (80k)', year:2020, price:2100000, mileage:80000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Strong premium used sedan; good entry point into BMW stock.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'BMW', model:'320 2020 (164k)', year:2020, price:1600000, mileage:164000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Higher-mileage BMW for price-sensitive premium buyers.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'BMW', model:'320 2024 (53k)', year:2024, price:2700000, mileage:53000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Near-new premium sedan stock with strong badge pull.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'BMW', model:'320 2024 (11k)', year:2024, price:3100000, mileage:11000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Low-km premium stock, ideal for showroom display.', images:[placeholder], listingStatus:'approved' },
      // ===================== AUDI — NEW =====================
      { category:'new', brand:'Audi', model:'A5 2026 Advanced', year:2026, price:3375000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Fastback', overview:'Elegant premium fastback/sedan line that sits well in a showroom next to BMW 4 Series.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Audi', model:'A6 2024 S Line', year:2024, price:4300000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Executive sedan with stronger luxury feel than entry premium cars.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Audi', model:'Q7 2026 S Line', year:2026, price:5250000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Large premium family SUV with prestige and practicality.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Audi', model:'RS e-Tron 2025 S Line', year:2025, price:6400000, mileage:0, fuelType:'Electric', transmission:'Automatic', bodyType:'SUV', overview:'Premium electric halo piece for a high-end showroom.', images:[placeholder], listingStatus:'approved' },
      // ===================== AUDI — USED =====================
      { category:'used', brand:'Audi', model:'Q3 2021', year:2021, price:1516000, mileage:50000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Compact premium SUV with safer demand than niche Audi body styles.', images:[placeholder], listingStatus:'approved' },
      // ===================== MERCEDES — NEW =====================
      { category:'new', brand:'Mercedes-Benz', model:'GLC 200 2026 Sport', year:2026, price:4930000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Safe premium SUV stock with strong badge demand.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Mercedes-Benz', model:'GLC 200 Coupe 2026 Sport', year:2026, price:5250000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Coupe SUV', overview:'More image-driven version of the GLC for showroom presence.', images:[placeholder], listingStatus:'approved' },
      { category:'new', brand:'Mercedes-Benz', model:'GLC 300 2026', year:2026, price:5400000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Upper-spec premium SUV, good as a high-ticket centerpiece.', images:[placeholder], listingStatus:'approved' },
      // ===================== MERCEDES — USED =====================
      { category:'used', brand:'Mercedes-Benz', model:'C 180 2020', year:2020, price:2100000, mileage:105000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Entry luxury sedan that gives your showroom premium presence without S-Class money.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Mercedes-Benz', model:'C 180 2019', year:2019, price:2350000, mileage:95000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Very useful premium used sedan for showroom image without huge capital lockup.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Mercedes-Benz', model:'CLA 200 2020', year:2020, price:1800000, mileage:88000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Coupe', overview:'Stylish premium entry car with stronger visual pull than a plain compact sedan.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Mercedes-Benz', model:'C 180 2025', year:2025, price:2582000, mileage:20000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Near-new premium used stock, useful when factory-new stock is too expensive.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Mercedes-Benz', model:'C 180 2015', year:2015, price:1500000, mileage:120000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Older premium stock for buyers entering Mercedes on lower budgets.', images:[placeholder], listingStatus:'approved' },
      // ===================== FERRARI — USED =====================
      { category:'used', brand:'Ferrari', model:'California T 2013', year:2013, price:3550000, mileage:75000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Convertible', overview:'Front-engine Ferrari that works as an exotic halo piece rather than normal showroom stock.', images:[placeholder], listingStatus:'approved' },
      // ===================== BENTLEY — USED =====================
      { category:'used', brand:'Bentley', model:'Flying Spur 2024', year:2024, price:18375000, mileage:13082, fuelType:'Petrol', transmission:'Automatic', bodyType:'Sedan', overview:'Ultra-luxury sedan with strong prestige value; this is special-order level stock, not normal rotation.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Bentley', model:'Continental 2010', year:2010, price:5200000, mileage:30000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Coupe', overview:'Older Bentley GT stock that can still work as a luxury statement car at a much lower entry point than new models.', images:[placeholder], listingStatus:'approved' },
      // ===================== ASTON MARTIN — NEW =====================
      { category:'new', brand:'Aston Martin', model:'Vantage Roadster 2020', year:2020, price:4750000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Roadster', overview:'Roadster version of the Vantage, positioned as a specialty luxury sports car.', images:[placeholder], listingStatus:'approved' },
      // ===================== ASTON MARTIN — USED =====================
      { category:'used', brand:'Aston Martin', model:'Vantage 2021', year:2021, price:9500000, mileage:11000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Coupe', overview:'Exotic sports coupe, mainly a halo/inventory prestige car rather than a volume seller.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Aston Martin', model:'Vantage 2019', year:2019, price:7600000, mileage:1000, fuelType:'Petrol', transmission:'Automatic', bodyType:'Coupe', overview:'Near-new or dealer-held Vantage stock, useful only in a high-end special-order section.', images:[placeholder], listingStatus:'approved' },
      // ===================== LAMBORGHINI — USED =====================
      { category:'used', brand:'Lamborghini', model:'Urus 2021', year:2021, price:20000000, mileage:15000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'One of the most recognizable exotic SUVs; pure halo inventory for a premium showroom.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Lamborghini', model:'Urus 2022 (14k)', year:2022, price:18500000, mileage:14000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Very low-km Urus, strong visual and status pull if you are building an ultra-luxury section.', images:[placeholder], listingStatus:'approved' },
      { category:'used', brand:'Lamborghini', model:'Urus 2022 (22k)', year:2022, price:18900000, mileage:22000, fuelType:'Petrol', transmission:'Automatic', bodyType:'SUV', overview:'Another realistic Egypt-market Urus entry, useful for benchmarking asking prices.', images:[placeholder], listingStatus:'approved' },
      // ===================== ROLLS-ROYCE — NEW =====================
      { category:'new', brand:'Rolls-Royce', model:'Cullinan 2024', year:2024, price:39000000, mileage:0, fuelType:'Petrol', transmission:'Automatic', bodyType:'Full-size SUV', overview:'Ultra-luxury flagship SUV; this is not normal inventory, this is pure statement stock.', images:[placeholder], listingStatus:'approved' },
    ];

    await Car.insertMany(cars);

    // Calculate minimumPrice for all cars (insertMany bypasses Mongoose middleware)
    const allCars = await Car.find({});
    for (const c of allCars) {
      c.minimumPrice = Math.floor(c.price * 0.9);
      await c.save();
    }

    console.log(`✅ Data Imported Successfully! ${cars.length} cars seeded.`);
    console.log('Master Admin: admin@prestigemotors.com / Admin@123');
    process.exit();
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

importData();
